name: Deploy to Pterodactyl
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to VPS (Pterodactyl server folder)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PTERO_SSH_HOST }}
          username: ${{ secrets.PTERO_USER }}
          password: ${{ secrets.PTERO_PASS }}
          source: "./*"
          target: "/var/lib/pterodactyl/volumes/03971a82-0157-4b60-9b87-fdd409880310"

      - name: Restart Pterodactyl server via API
        run: |
          curl -X POST "${{ secrets.PTERO_PANEL_URL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/power" \
          -H "Authorization: Bearer ${{ secrets.PTERO_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"signal": "restart"}'
